* In person meeting - <2026-09-13 Sun>                                              :in-person:
:PROPERTIES:
:PROJECT:  p2poolv2
:ATTENDEES: jungly, johnnysantoss, msgilligan, lucas, localhost
:END:

** Agenda
- Design discussions on sharechain and market place design
- Blockers
- Wallet requirements
- Testnet4 setup
- Coinpool/statechain discussions

** Discussion Notes

*** Design discussions

We discussed in depth the approach to managing UTXOs and any design
changes we could bring in to help make the market place design easier
or pricing model simpler.

**** Unspent Output Age Tracking and Demurrage for UTXO Fungibility

Age is important to track so that miners and market place can
determine how close the UTXO is to expiry.

The following were discussed for UTXOs age:

1. How can we let miners spend UTXOs and yet retain their "age" so
   that the age is directly captured in unspent outputs.
2. Should we introduce demurrage in the UTXOs to solve the problem of
   tracking UTXO age.
3. How can we handle change and mixing of UTXOs and still determine
   the age of the unspent outputs.
4. If we add demurrage to UTXOs and reduce the amount of output's
   value that can spent based on its depth, can we make all outputs
   completely fungible.

We also discussed how we should keep the complications of determine
price based on depth of an output to the higher layers and not to roll
them into the sharechain consensus. By making outputs fungible, we
remove the concept of time or bitcoin block height based "buckets" in
the marketplace.   
   
***** Conclusion

The current implementation determines the age of a coinbase from the
block height it was created in. We index that in tx metadata and from
then on we can find the root height of an unspent output as the height
the coinbase that created the first UTXO in the chain of the UTXOs
leading to the unspent output. These are indexed and fast to query in
the store.

For now the design discussions concluded we are OK with the above
design. We can revisit if we run into some market place design
requirements that can not be addressed with the current design.

We will revisit the need for removing buckets from marketplace once we
are in discussion with market maker and fintech people. For the
moment, jungly backed the idea of keeping buckets in the marketplace
and keeping the sharechain as simple and as close to the bitcoin
design as possible.

**** Fee Calculation

The question here is when an output is spent, how do we differentiate
the fees of an old output vs a new output?

The reasons to differentiate is to discourage a DoS attack by a holder
of a UTXO as it is going out of the PPLNS window and can't be spent
anymore.

***** Conclusion

We need to apply a linear increase in fees from depth 1 to depth
120,960, going from 1 vsat/byte to an amount to be determined. As the
outputs gets older, it has to pay more fee to create new outputs. This
avoids a griefing attack by a miner who knows their output will be
worthless soon.

We acknowldge this will create a double whammy for the miners, as
being closer to expiry it will fetch a bad price and now even to spend
it, they lose more "sats" of the share coin to chain fee.

https://github.com/p2poolv2/p2poolv2/issues/646


**** Rich List Attack

This is a known attack where a large miners does a sybil attack and
pretends to be multiple miners - filling all the slots of the bitcoin
coinbase and then refusing to buy the shares from smaller miners. This
will result in the death of a specific p2poolv2 instance. This was
identified first by bluematt in a btcplusplus event in Vienna.

1. Random selection: We discussed bluematt's proposal to try to figure
   it pseudo random + hashrate weighted selection of miners can
   work. We don't yet have a full solution where the approach can
   work.

2. Well known market makers: One more idea discussed was to have a
   handful of well known market makers who always get a slot in the
   coinbase. We don't need to change anything in the code, it is more
   a community communication that these market makers are well known
   actors, and miners should consider selling shares to them so the
   pool remains healthy. This does create some sort of semi-trusted
   third parties, and we are aware of this weakness.

3. Statechains: If we are doing semi trusted third parties what if we
   go into a state chain based design to enable scalable
   payouts. Unfortunately, we didn't get around to discussing the ins
   and outs of the proposal.

4. We also discussed working with the ARK team to figure out if we can
   come up with some clever new design. Our current interaction with
   Second has been limited to requesting changes in their tx templates
   to include a generic HTLC that we can use for swapping sharechain
   UTXOs with VTXOs.


***** Conclusion

Created an issue to decide on the defense against rich list attack. We
will later add one for implementation as needed: 

https://github.com/p2poolv2/p2poolv2/issues/647

**** Wallet Requirements Docs

We needed to define an MVP for our wallet work. We agreed to limit the
wallet to construct txs that spend a single input and create a single
output.

We agreed we will limit the wallet to sharechain only, leaving
the bitcoin transaction handling to other existing bitcoin wallets.

We also agreed we will use descriptors to wallet interchange.

There is an issue tracking the agreed upon steps to take
https://github.com/p2poolv2/p2poolv2/issues/648.

**** Wallet Support API

We need to implement bitcoind and electrum compatible API endpoints so
wallets can be built.

This requires careful schema work and some API selection. Created two issues for this:

https://github.com/p2poolv2/p2poolv2/issues/655 and
https://github.com/p2poolv2/p2poolv2/issues/656


**** Validate Shares With Bitcoin Block Heights

Murch pointed out a couple of corner cases. One in chain reorg and
another for block validation.

The chain reorg concern was that we should be able to reorg a block
with parent more than one deep. This was recently seen as two depth
reorgs on bitcoin. Our implementation handles this situation.

The other concern raised has deeper implications, including how we
handle block template / work propagation in p2poolv2. The question
raised was: If an adversarial fork of bitcoin keeps mining on
p2poolv2 - will they receive rewards for work submitted to p2poolv2
even if their work is based on previous blocks that are not on the
bitcoin chain anymore? During the discussion we realised we need to
address this and also need to document it in detail so we can get
feedback.

We discussed a solution where we invalidate share blocks that have
bitcoin previous block hash not reachable from the current tip. This
would mean the work submitted for adversarial bitcoin chain will be
marked invalid on p2poolv2 and therefore won't receive any reward from
p2poolv2.

There are some details to think through here and also to analyse how
the solution might circumvent the need for full bitcoin block template
/ work propagation in p2poolv2 to validate share blocks. Therefore I
have created two issues here. One to document the the solution and
it's implication in the context of share chain validation and second
to implement the solution.

https://github.com/p2poolv2/p2poolv2/issues/652
https://github.com/p2poolv2/p2poolv2/issues/653


**** Compact Blocks, Bitcoin Kernel & Context Free Block Validation

Questions were raised if we need to continue implementing compact
block propagation for bitcoin template / work. The idea of using
p2pool classic's approach to propagate txs sets and txs set deltas for
synchronising the validation states was discussed, but not fully
considered. The question of if we need to run full bitcoin block
validation itself became more central. It was pointed out that there
is no API to ask Core to only validate a block, or a compact block,
without asking it to try and advance the chain using
submitblock. Using submit block for validation of weak blocks will
probably stop at PoW check and won't run all the validations [we
should check this].

Another idea discussed was to use bitcoin kernel to run context free
validation, but that still means we need to rehydrate compact blocks
in p2poolv2 layer, which means replicating bitcoin mempool in
p2poolv2. Some were against inheriting so much complexity and a big
potential source of consensus discrepancies.

Meanwhile it was agreed we should target compact block support for
share block propagation. It was pointed this is an optimisation that
we probably don't need so early in the project. As a reminder, our
blocks are limited to 200kB.

We already have issues and draft PRs to address compact blocks for
bitcoin. Depending on 652's conclusion, we will need to revisit
these. No new issues created here.

I'll reasses how far along is the implementation of compact blocks for
share chain and depending on the time already spent make a call on if
we continue now or start later.

**** Pool Factory

Sean presented the idea of using a pool factory to manage payouts for
miners. I don't have the details here, but there were some cool
approaches Sean was thinking of taking. Sean plans to write them down,
so we can discuss them again once the structures are more clear.

**** Testnet4

The idea of point some hashrate to testnet4 mining through p2poolv2
was discussed. It was pointed out that it was a way to draw attention
to our work at the same time show how permissionless mining can be
through p2poolv2.

***** Conclusion

We should prepare some p2poolv2 nodes with the Core patch by
batmanbytes and point some hashrate to it. There were some volunteers
in the room willing to help, so we should be able to do something.

https://github.com/p2poolv2/p2poolv2/issues/657

** Action Items

Issues created as work to do are linked inline with the discussion
notes above.
